# Generated by Django 2.1.7 on 2019-10-27 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome do funcionário')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('pontuacao', models.FloatField(blank=True, default=0, verbose_name='Pontuação colaborador')),
                ('maxcoins', models.FloatField(blank=True, default=0, verbose_name='MaxCoins colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome do departamento')),
                ('admin', models.BooleanField(verbose_name='Departamento Admin')),
            ],
        ),
        migrations.CreateModel(
            name='LancamentoPontuacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição do lançamento')),
                ('data_lancamento', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_maxliga.Colaborador', verbose_name='Colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome da liga')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPonto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome tipo de ponto')),
                ('qtd_ponto', models.FloatField(blank=True, default=0, verbose_name='Quantidade de pontos')),
                ('qtd_maxcoins', models.FloatField(blank=True, default=0, verbose_name='Quantidade de MaxCoins')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
            ],
        ),
        migrations.AddField(
            model_name='lancamentopontuacao',
            name='tipo_ponto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_maxliga.TipoPonto', verbose_name='Tipo de ponto'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_maxliga.Departamento', verbose_name='Cargo do colaborador'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='liga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_maxliga.Liga', verbose_name='Liga do colaborador'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
