# Generated by Django 2.1.7 on 2019-10-27 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_maxliga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentopontuacao',
            name='avaliador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliador_colaborador', to='app_maxliga.Colaborador', verbose_name='Avaliador'),
        ),
        migrations.AlterField(
            model_name='lancamentopontuacao',
            name='colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaborador_colaborador', to='app_maxliga.Colaborador', verbose_name='Colaborador'),
        ),
    ]
