# Generated by Django 2.1.12 on 2019-10-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_maxliga', '0002_auto_20191027_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentopontuacao',
            name='descricao',
            field=models.TextField(max_length=300, verbose_name='Descrição do lançamento'),
        ),
    ]
